name: Markdown to PDF

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*

jobs:
  build:
    name: md to formatted pdf
    runs-on: ubuntu-latest
    env:
      working-directory: ./Specifications
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Set version
        id: set_version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "Specifications"
          # Named version, will be used as suffix for name version tag
          namespace: msr-spec
          # Indicate whether short tags like 'v1' should be supported. If false only full
          # tags like 'v1.0.0' will be recognized.
          short_tags: true
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
      
      - run: mkdir -p ${{ env.working-directory }}/templates
      
      - uses: suisei-cn/actions-download-file@v1
        id: download_file  # Remember to give an ID if you need the output
        name: Download the file
        with:
          url: "[template for pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.0.0/Eisvogel.zip)!"
          target: public/
          auto-match: true
      
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq public/${{ steps.download_file.outputs.filename }} -d ${{ env.working-directory }}/templates
      
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@master
        with:
          args: '-s -o msr-specification.pdf msr-specification.md --from markdown --template eisvogel --data-dir ${{ env.working-directory }}/'
          working-directory: ${{ env.working-directory }}
            
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.set_version.outputs.version }}
          release_name: Release ${{ steps.set_version.outputs.version }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Specifications/msr-specification.pdf
          asset_name: msr-specification.pdf
          asset_content_type: application/pdf
